name: 打包成win可执行文件

on:
  #push:
  #  branches: [ main ]  # 可以指定分支，如'main'或'master'，留空则表示所有分支
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build-windows:

    runs-on: windows-latest

    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.6.0
        with:
          python-version: 3.9
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'XiaoYi-win-x86-64'
          options: XiaoYi.spec
          
