name: 打包成exe并上传至Release

on:
  push:
    tags: [ '*' ] # 确保在打标签时触发此工作流程
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pyinstaller-build-and-upload-windows:

    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python-version: '3.9'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'XiaoYi-win-x86-64'
          options: --onefile --name "XiaoYi"

      - name: Upload Windows Executable to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/XiaoYi.exe
          asset_name: XiaoYi-win-x86-64.exe
          tag: ${{ github.ref }}
          overwrite: true
