name: 打包成linux并上传至Release

on:
  push:
    tags: [ '*' ] # 确保在打标签时触发此工作流程
  workflow_dispatch:

permissions:
  contents: write

jobs:

  pyinstaller-build-and-upload-ubuntu:

    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies for PyAudio
        run: |
          sudo apt-get update
          sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
        if: runner.os == 'Linux'
  
    
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python-version: '3.9'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'XiaoYi-linux-x86-64'
          options: --onefile, --name "XiaoYi"

      - name: Upload Linux Executable to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }} # 使用GitHub Secrets存储的Token以安全地访问API
          file: dist/XiaoYi # 假设打包后的文件位于`dist`目录下并命名为`XiaoYi`
          asset_name: XiaoYi-linux-x86-64 # 上传的资产名称
          tag: ${{ github.ref }} # 使用触发此工作流的标签作为Release标签
          overwrite: true # 如果存在同名文件，则允许覆盖
