name: 打包成exe

on:
  push:
    branches: [ main ]  # 可以指定分支，如'main'或'master'，留空则表示所有分支
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pyinstaller-build-windows:

    runs-on: windows-latest

    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python-version: '3.9'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'XiaoYi-win-x86-64'
          options: --onefile, --name "XiaoYi"
          
  pyinstaller-build-ubuntu:

    runs-on: ubuntu-latest

    steps:
      - name: Install system dependencies for PyAudio
        run: |
          sudo apt-get update
          sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
        if: runner.os == 'Linux'
  
    
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python-version: '3.9'
          spec: 'main.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'XiaoYi-linux-x86-64'
          options: --onefile, --name "XiaoYi"
