name: 打包成exe并发布至Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write  # 需要写权限以创建或更新Release资产

jobs:
  pyinstaller-build-and-upload:

    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Executable
      run: |
        pip install pyinstaller
        pyinstaller --onefile --name XiaoYi main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: XiaoYi.exe
        path: dist/XiaoYi.exe

    - name: Create GitHub Release
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/XiaoYi.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
