name: Upload Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pyinstaller-build:

    runs-on: windows-latest

    steps:
    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python-version: '3.x'
        spec: 'main.py'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'XiaoYi'
        options: --onefile, --name "XiaoYi" --windowed --hidden-import=numpy.core._multiarray_umath main.py
